### ISSUE TITLE
迁移到 gulp-spm

### ISSUE THREAD

**Issue by popomore** [spmjs/gulp-spm#21]
1. [x] 改名成 gulp-spm
2. [x] 内置 father 解析，方便调用
   
   ```
   gulp.src(file)
   .pipe(spm(opt))
   .pipe(gulp.dest(dir))
   ```
3. [x] pkg 可通过 file 传递
4. [x] 可配置参数
   
   ```
   var defaults = {
   pkg: null,
   cwd: process.cwd(),
   ignore: [],
   skip: [],
   include: '',
   idleading: '',
   stream: null,
   rename: '',
   moduleDir: 'spm_modules'
   };
   ```
5. [x] pkg 可公用全局，允许外部传入
6. [x] dest 集成进 gulp-spm
7. [x] 添加 standalone 和 umd 参数
8. [x] 默認集成 jsx 解析 https://github.com/yiminghe/gulp-reactify
9. [x] father@0.10

**Comment by piaer** [comment]
请问能给个 gulp-spm 的样例吗
