### ISSUE TITLE
global 参数的替换名如果是 monitor，不会被替换

### ISSUE THREAD

**Issue by sorrycc** [spmjs/gulp-spm#31]
比如：`spm b --standalone a.js --global sai:monitor` 不行，`aspm b --standalone a.js --global sai:monitorr` 可以。

**Comment by sorrycc** [comment]
@popomore `monitor` 这个单词有特殊处理?

**Comment by popomore** [comment]
没有这个关键字吧

**Comment by hotoo** [comment]
@sorrycc 问题解决了么？

**Comment by sorrycc** [comment]
https://github.com/seajs/crequire/issues/3
测试了下是 crequire 的问题， @army8735

**Comment by sorrycc** [comment]
测试过，已经可以了。 @hotoo 重装下 spm 吧。
